IF
	Global("k9_ARwolves","ar1801",0)  	DifficultyGT(NORMAL)
THEN
	RESPONSE #100
		SetGlobal("k9_ARwolves","ar1801",1)
 	SetRestEncounterProbabilityDay(14)
 	SetRestEncounterProbabilityNight(14)

END

IF
	Global("k9_ARwolves","ar1801",0)     DifficultyGT(HARD)
THEN
	RESPONSE #100
		SetGlobal("k9_ARwolves","ar1801",1)
 	SetRestEncounterProbabilityDay(18)
 	SetRestEncounterProbabilityNight(18)

END

